# Generated by Django 2.1.5 on 2019-01-19 09:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('update_date_time', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(choices=[(0, '説明'), (1, 'リンク')], default=0)),
                ('titele', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('disp_order_no', models.IntegerField(default=0)),
                ('update_date_time', models.DateField(default=datetime.date.today)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.Animal')),
            ],
        ),
    ]
